"""added_interests_table

Revision ID: 2d6c952ed814
Revises: 9089290a075b
Create Date: 2021-06-02 13:46:42.704291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6c952ed814'
down_revision = '9089290a075b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interests', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    # ### end Alembic commands ###
